
pacman::p_load(here, tidyverse, pheatmap, reshape2)
source(file.path(here(), "analyses", "pullSHEP.R"))

data <- dat_fin |> 
  select(need_vars, risk_vars, WEIGHT, WBS_total, RateHealth_T1, RateMentalHealth_T1, SURVID) |> 
  drop_na()

needs <- tibble(name = need_vars, y = "n") |> 
  slice_head(n=-1) |> 
  mutate(newname = str_remove(paste0(y, "_", name), "_T1"))

risks <- tibble(name = risk_vars, y = "r") |> 
  slice_head(n=-1) |> 
  mutate(newname = str_remove(paste0(y, "_", name), "_T1"))

needs <- data |> 
  select(need_vars, SURVID, WEIGHT) |> 
  pivot_longer(cols = -c(SURVID, WEIGHT)) |>
  left_join(needs, by = "name") |> 
  select(-c(name, y)) |> 
  pivot_wider(names_from = newname, values_from = value)

risks <- data |> 
  select(risk_vars, SURVID, WEIGHT) |> 
  pivot_longer(cols = -c(SURVID, WEIGHT)) |>
  left_join(risks, by = "name") |> 
  select(-c(name, y)) |> 
  pivot_wider(names_from = newname, values_from = value)

outcomes <- data |> 
  select(SURVID, WEIGHT, RateMentalHealth_T1, WBS_total)

data <- inner_join(needs, outcomes) |> inner_join(risks)

#### some manual cleaning for risks
data$r_GetCaregiving <- (fct_collapse(data$r_GetCaregiving, "1" = c("1", "8")))
data$r_GetChildcare <- (fct_collapse(data$r_GetChildcare, "1" = c("1", "8")))
data$r_FindWork <- (fct_collapse(data$r_FindWork, "1" = c("1", "8")))
for(i in 18:ncol(data)){
  data[,i] <- droplevels(data[,i])
}
data$r_HaveHousing <- factor(5 - as.numeric(data$r_HaveHousing), levels = c(1, 2, 3, 4))
data$r_AccessInternet <- factor(5 - as.numeric(data$r_AccessInternet), levels = c(1, 2, 3, 4))
data$r_LegalNeed <- factor(3 - as.numeric(data$r_LegalNeed), levels = c(1, 2))
#### some manual cleaning for neeeds
data <- data |> mutate(across(starts_with("n"), 
                              ~ fct_collapse(as.factor(.), "2" = c("2", "3"))))
#### some manual cleaning for outcomes
data$o_mh <- as.factor(6 - as.numeric(data$RateMentalHealth_T1))
data$o_wb <- cut(data$WBS_total, breaks = c(0, 25, 50, 75, 100), include.lowest = TRUE, 
                 labels = c("1", "2", "3", "4"))
data <- data |> select(-c(RateMentalHealth_T1, WBS_total))
data <- data |> select(c("SURVID", "WEIGHT", colnames(needs)[3:15], "o_mh", "o_wb", colnames(risks)[3:18]))

data_cor <- lavaan::lavCor(data.frame(data[,str_detect(colnames(data), "n_|WEIGHT")]), 
                           ordered = colnames(data)[str_detect(colnames(data), "n_")], 
                           sampling.weights = "WEIGHT")



# ---------------------------------------------------------
# Assuming data_cor is already generated by lavaan::lavCor
# ---------------------------------------------------------

# 1. Convert correlations to distances (Distance = 1 - r)
# A correlation of 0.75 becomes a distance of 0.25.
dist_mat <- as.dist(1 - data_cor)

# 2. Perform hierarchical clustering
# "complete" linkage ensures that EVERY pair in a cluster has a correlation of at least 0.75
hc <- hclust(dist_mat, method = "complete")

# 3. Cut the tree at a height of 0.25
clusters <- cutree(hc, h = 0.25)

# 4. Create an annotation dataframe for pheatmap so the clusters are color-coded
cluster_info <- data.frame(Cluster = as.factor(clusters))
rownames(cluster_info) <- rownames(data_cor)


clean_names <- c(
  "Paying for Basics", 
  "Adult Caregiving", 
  "Childcare", 
  "Finding/Keeping Work", 
  "Paying for Food", 
  "Getting/Maintaining Housing", 
  "Transportation", 
  "Home Internet Access", 
  "Social Isolation", 
  "Loneliness", 
  "Managing Discrimination", 
  "Legal Assistance", 
  "Education/Job Training"
)

# Assuming your matrix is already in the same order as the variables above:
rownames(data_cor) <- clean_names
colnames(data_cor) <- clean_names
rownames(cluster_info) <- clean_names

# Define the 8 colorblind-friendly hex codes
cb_palette <- c(
  "#999999", # Grey
  "#E69F00", # Orange
  "#56B4E9", # Sky Blue
  "#009E73", # Bluish Green
  "#F0E442", # Yellow
  "#0072B2", # Blue
  "#D55E00", # Vermillion
  "#CC79A7"  # Reddish Purple
)

# Create a mapping list for pheatmap
# IMPORTANT: The name "Cluster" here must exactly match the column name 
# in your 'cluster_info' dataframe that you created earlier.
my_cluster_colors <- list(
  Cluster = c(
    "1" = cb_palette[1],
    "2" = cb_palette[2],
    "3" = cb_palette[3],
    "4" = cb_palette[4],
    "5" = cb_palette[5],
    "6" = cb_palette[6],
    "7" = cb_palette[7],
    "8" = cb_palette[8]
  )
)



# 5. Generate the updated heatmap
cor_map_needs <- pheatmap(
  data_cor[rownames(cluster_info |> arrange(Cluster)), rownames(cluster_info |> arrange(Cluster))],
  #main = "2026-03-06: Polychoric Correlation Heatmap\n(Clusters represent r >= 0.75)",
  fontsize = 18,
  legend = FALSE,
  border_color = "black",
  number_color = "black",
  display_numbers = TRUE,
  cluster_rows = FALSE,             # Use our custom distance tree for rows
  cluster_cols = FALSE,             # Use our custom distance tree for columns
  annotation_row = cluster_info,    # Show cluster colors on the left
  annotation_col = cluster_info,     # Show cluster colors on the top,
  annotation_colors = my_cluster_colors
)
# 
# 
# 
# cor_map_needs <- pheatmap(
#   data_cor,
#   main = "2026-03-06: Polychoric Correlation Heatmap: Outcomes vs Needs\n(SURVEY WEIGHTED, SLIGHTLY DIFFERENT FROM PREVIOUS NUMBERS)",
#   fontsize = 12,
#   number_color = "black",
#   display_numbers = TRUE,  # Show the correlation coefficient in each cell
#   cluster_rows = TRUE,   # Cluster rows to group similar variables
#   cluster_cols = TRUE#,   # Cluster columns
#   #color = colorRampPalette(c("#67001F", "white", "#053061"))(50) # Red-White-Blue palette
# )
# 
if(FALSE){
  factor <- 1.5
  ggsave("C:/Users/VHAPTHPURKAS/OneDrive - University of Pittsburgh/Research/2026_surveyCD/analyses/2026_03_02_clusterOutcomeNeed_weighted.pdf",
         cor_map_needs,
         height = factor*8.5,
         width = factor*10,
         units = "in",
         device = "pdf")
}

# 
# 
# 
# data_cor <- lavaan::lavCor(data.frame(data[,str_detect(colnames(data), "r_|o_|WEIGHT")]), 
#                            ordered = colnames(data)[str_detect(colnames(data), "r_|o_")], 
#                            sampling.weights = "WEIGHT")
# 
# cor_map_risks <- pheatmap(
#   data_cor,
#   main = "2026-03-06: Polychoric Correlation Heatmap: Outcomes vs Risks\n(SURVEY WEIGHTED, SLIGHTLY DIFFERENT FROM PREVIOUS NUMBERS)",
#   fontsize = 12,
#   number_color = "black",
#   display_numbers = TRUE,  # Show the correlation coefficient in each cell
#   cluster_rows = TRUE,   # Cluster rows to group similar variables
#   cluster_cols = TRUE#,   # Cluster columns
#   #color = colorRampPalette(c("#67001F", "white", "#053061"))(50) # Red-White-Blue palette
# )
# 
# if(FALSE){
#   factor <- 1.5
#   ggsave("C:/Users/VHAPTHPURKAS/OneDrive - University of Pittsburgh/Research/2026_surveyCD/analyses/2026_03_02_clusterOutcomeRisk_weighted.pdf", 
#          cor_map_risks, 
#          height = factor*8.5,
#          width = factor*10, 
#          units = "in", 
#          device = "pdf")
# }
# 
